### ISSUE TITLE
Cover Page

### ISSUE THREAD

**Issue by xvrabcov** [xvrabcov/fithesis#19]
Looking at the current layout of the cover pages, it would perhaps be prudent to unify them to more closely resemble the reworked title pages.

**Comment by Witiko** [comment]
We should add the title of the work to the cover page similarly to the title page.   
If time permits, we should patch the cover page for FI MU to include the monochromatic faculty seal.

**Comment by Witiko** [comment]
Here is a picture of the optical center, where the most prominent object should be placed: <http://web.quick.cz/iveta_kulhava/Typografie/Zasady.htm#optickystred>
