### ISSUE TITLE
Title Page

### ISSUE THREAD

**Issue by xvrabcov** [xvrabcov/fithesis#2]
With the implementation of the _JVS 2018_, it would be nice if at a first glance the title pages of theses seemed unified (also, similarity to the Word template). In [this example](https://www.overleaf.com/read/vcsvqjwqbcgj
) is a possible look of the implementation. In fithesis/Change Logs/titlePage-changes.txt, all modified files are listed.
The example does not strictly adhere to the regulations of the Law (PF) and Medical (LF) Faculties, as they want the department name and the programme on the top of the page, but as only a small portion of their students use the LaTeX templates, it is not a major concern.

**Comment by Witiko** [comment]
I did not implement the possibility for the department name and the programme to be displayed on the top of the page for the Faculty of Law and the Faculty of Medicine in #8. I am reopening the issue, so that it can be closed after this is fixed.
