### ISSUE TITLE
Page Numbering

### ISSUE THREAD

**Issue by xvrabcov** [xvrabcov/fithesis#45]
Five of the faculties (LAW, MED, SCI, ECON, FSPS) have specified page numbering. It might be better to implement it in accordance with that.

Also, it might be prudent to modify the Number of Pages shown in bibEntry. Currently it does not count pages in preamble into the total number.

**Comment by Witiko** [comment]
> Also, it might be prudent to modify the Number of Pages shown in bibEntry. Currently it does not count pages in preamble into the total number.

I don't know the current requirements, but in fithesis3, we showed front matter pages and main matter pages in the bibEntry separately: the front matter pages would be displayed as lower-case roman numbers and the main matter pages would be displayed as arabic numbers. We have special macros for it: `\thesis@pages@preamble` and `\thesis@pages` (also `\thesis@pages@postamble`), take a look in [the documentation](http://mirrors.ctan.org/macros/latex/contrib/fithesis/fithesis.pdf): 🙂 

![Untitled](https://user-images.githubusercontent.com/603082/118405288-72e66f80-b677-11eb-9c97-0fd42fae7b33.png)

**Comment by Witiko** [comment]
For a reference: all faculties have the title page as the first page of the front matter since https://github.com/xvrabcov/fithesis/pull/43.

**Comment by xvrabcov** [comment]
Five of the faculties (FSPS, LAW, MED, SCI, ECON) have specifications for the page numbering.
FSPS/SCI - visible numbering from the first page of ToC (counting from the title page)
LAW/MED - numbering from the page with declaration (begins with "1")
ECON - visible numbering from the introduction (counting from the title page)

This can be implemented with usage of the `\thesis@xpatch` macro.

**Comment by Witiko** [comment]
> FSPS/SCI - visible numbering from the first page of ToC (counting from the title page)   
> LAW/MED - numbering from the page with declaration (begins with "1")

Should be fixed by #50.

> ECON - visible numbering from the introduction (counting from the title page)

This is the current behavior.
